version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coordinadora
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --save "" --appendonly no
    restart: always
    ports:
      - "6379:6379"
